// <auto-generated />
namespace NAControl.Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _23102017_MEETING : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23102017_MEETING));
        
        string IMigrationMetadata.Id
        {
            get { return "201710231159162_23102017_MEETING"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
